# Generated by Django 4.2.1 on 2023-12-12 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previousyearpaper",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="previousyearpaper",
            name="links",
        ),
        migrations.RemoveField(
            model_name="studymaterial",
            name="exam_who_can_refer",
        ),
        migrations.RemoveField(
            model_name="studymaterial",
            name="links",
        ),
    ]
