# Generated by Django 4.2.1 on 2023-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_previousyearpaper_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exams_who_can_refer',
            field=models.ManyToManyField(to='exam.exam'),
        ),
    ]
