# Generated by Django 4.2.1 on 2023-12-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_exams_who_can_refer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStep1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamStep2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step2', to='exam.examstep1')),
            ],
        ),
        migrations.CreateModel(
            name='ExamStep3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper', models.FileField(upload_to='exam/question_papers/')),
                ('answer_key', models.FileField(upload_to='exam/answer_keys/')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step3', to='exam.examstep1')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamDate',
        ),
        migrations.DeleteModel(
            name='ExamPattern',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='PaymentMode',
        ),
        migrations.DeleteModel(
            name='PreviousYearPaper',
        ),
        migrations.DeleteModel(
            name='RegistrationCategory',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
