# Generated by Django 4.2.1 on 2023-12-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_examstep1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstep3',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examstep3',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
