# Generated by Django 4.2.1 on 2023-12-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examstep3_answer_examstep3_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examstep3',
            old_name='answer',
            new_name='faq_answer',
        ),
        migrations.RenameField(
            model_name='examstep3',
            old_name='question',
            new_name='faq_question',
        ),
    ]
