# Generated by Django 4.2.1 on 2023-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_rename_answer_examstep3_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstep1',
            name='exam_official_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examstep1',
            name='registration_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
