# Generated by Django 4.2.1 on 2023-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_examstep1_brochure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstep1',
            name='exam_frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quaterly', 'Quaterly'), ('biannual', 'Biannual')], null=True),
        ),
        migrations.AlterField(
            model_name='examstep1',
            name='payment_modes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
