# Generated by Django 4.2.1 on 2023-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStep1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('established_year', models.PositiveIntegerField()),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStep2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_type', models.CharField(max_length=50)),
                ('accreditation', models.CharField(max_length=50)),
                ('affiliated_university', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStep3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_offered', models.TextField()),
                ('admission_criteria', models.TextField()),
                ('facilities_provided', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStep4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notable_alumni', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStep5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_logo', models.ImageField(upload_to='college_logos/')),
                ('college_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='alumni_degree',
        ),
        migrations.RemoveField(
            model_name='college',
            name='application_process_degree',
        ),
        migrations.RemoveField(
            model_name='college',
            name='course',
        ),
        migrations.RemoveField(
            model_name='college',
            name='cutoffs_degree',
        ),
        migrations.RemoveField(
            model_name='college',
            name='degree_offered',
        ),
        migrations.RemoveField(
            model_name='college',
            name='faculties_background',
        ),
        migrations.RemoveField(
            model_name='college',
            name='faculties_specialisation',
        ),
        migrations.RemoveField(
            model_name='college',
            name='locations_state',
        ),
        migrations.RemoveField(
            model_name='college',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='college',
            name='placement_degree',
        ),
        migrations.RemoveField(
            model_name='college',
            name='reviews_course_taken',
        ),
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
        migrations.RemoveField(
            model_name='college',
            name='subject_wise_cutoffs_category',
        ),
        migrations.RemoveField(
            model_name='college',
            name='subject_wise_cutoffs_subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exams_who_can_refer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
