# Generated by Django 4.2.1 on 2023-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_collegestep1_collegestep2_collegestep3_collegestep4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPercentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('category_1', 'Category 1'), ('category_2', 'Category 2'), ('category_3', 'Category 3')], max_length=20)),
                ('percentile', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('State1', 'State 1'), ('State2', 'State 2')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_1', models.TextField(blank=True, max_length=50, null=True)),
                ('address_line_2', models.TextField(blank=True, max_length=50, null=True)),
                ('landmark_locality', models.TextField(blank=True, max_length=10, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWiseCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('subject_1', 'Subject 1'), ('subject_2', 'Subject 2'), ('subject_3', 'Subject 3')], max_length=20)),
                ('category', models.CharField(choices=[('category_1', 'Category 1'), ('category_2', 'Category 2'), ('category_3', 'Category 3')], max_length=20)),
                ('cutoff_percentile', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='collegestep2',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='collegestep2',
            name='affiliated_university',
        ),
        migrations.RemoveField(
            model_name='collegestep2',
            name='college_type',
        ),
        migrations.RemoveField(
            model_name='collegestep2',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='collegestep2',
            name='email',
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='closes',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='instagram_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='landmark_locality',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='linkedin_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='main_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='management_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='management_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='management_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='management_role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='opens',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='pan_card_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='pan_card_upload',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/'),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='pinterest_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='short_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='twitter_handle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='youtube_channel',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='application_process_degree_branch',
            field=models.CharField(blank=True, choices=[('degree_branch_1', 'Degree/Branch 1'), ('degree_branch_2', 'Degree/Branch 2'), ('degree_branch_3', 'Degree/Branch 3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='application_process_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='batch_strength',
            field=models.CharField(blank=True, choices=[('less_than_50', 'Less than 50'), ('50_to_100', '50 to 100'), ('100_to_150', '100 to 150'), ('150_and_above', '150 and above')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='course_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('5_years', '5 Years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('distance_learning', 'Distance Learning')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='cutoff_parameter',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='date_description',
            field=models.CharField(blank=True, choices=[('start', 'Start Date'), ('end', 'End Date'), ('event', 'Event Date')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='degree_offered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='eligibility_criteria',
            field=models.CharField(blank=True, choices=[('eligibility_1', 'Eligibility Criteria 1'), ('eligibility_2', 'Eligibility Criteria 2'), ('eligibility_3', 'Eligibility Criteria 3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='eligibility_criteria_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='event_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='news',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='news_category',
            field=models.CharField(blank=True, choices=[('very_imp', 'Very Important'), ('imp', 'Important'), ('medium_imp', 'Medium Important'), ('less_imp', 'Less Important')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='other_entrance_criteria',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='previous_cutoff_degree_branch',
            field=models.CharField(blank=True, choices=[('degree_branch_1', 'Degree/Branch 1'), ('degree_branch_2', 'Degree/Branch 2'), ('degree_branch_3', 'Degree/Branch 3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='starts_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='total_fees',
            field=models.CharField(blank=True, choices=[('less_than_1L', 'Less than 1 Lakh'), ('1L_to_2L', '1 Lakh to 2 Lakhs'), ('2L_to_3L', '2 Lakhs to 3 Lakhs'), ('3L_to_4L', '3 Lakhs to 4 Lakhs'), ('4L_to_5L', '4 Lakhs to 5 Lakhs'), ('5L_and_above', '5 Lakhs and above')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='state',
            field=models.CharField(blank=True, choices=[('State1', 'State 1'), ('State2', 'State 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='days_of_operation',
            field=models.ManyToManyField(blank=True, to='college.weekday'),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='locations',
            field=models.ManyToManyField(blank=True, to='college.location'),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='other_links',
            field=models.ManyToManyField(blank=True, to='college.otherlink'),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='category_percentile',
            field=models.ManyToManyField(blank=True, to='college.categorypercentile'),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='exams_through_admission',
            field=models.ManyToManyField(blank=True, to='college.entranceexam'),
        ),
        migrations.AddField(
            model_name='collegestep2',
            name='subject_wise_cutoff',
            field=models.ManyToManyField(blank=True, to='college.subjectwisecutoff'),
        ),
    ]
