# Generated by Django 4.2.1 on 2023-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alumni_checklist_entranceexamchoice_facility_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='person',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='available_facilities',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='person',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='collegestep4',
            options={},
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='locations',
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='category',
            field=models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='cutoff_percentile',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='degree_branch',
            field=models.CharField(blank=True, choices=[('Degree1', 'Degree 1'), ('Degree2', 'Degree 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='parameter_of_cutoffs',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='percentile',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='subject',
            field=models.CharField(blank=True, choices=[('subject1', 'Subject 1'), ('subject2', 'Subject 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='background',
            field=models.CharField(blank=True, choices=[('background1', 'Background 1'), ('background2', 'Background 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='base_city',
            field=models.CharField(blank=True, choices=[('city1', 'City 1'), ('city2', 'City 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='faculty_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='specialisation',
            field=models.CharField(blank=True, choices=[('specialisation1', 'Specialisation 1'), ('specialisation2', 'Specialisation 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='academics_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='accommodation_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='available_facilities',
            field=models.ManyToManyField(to='college.facility'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='category',
            field=models.ManyToManyField(to='college.photocategory'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='course_taken',
            field=models.CharField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='faculty_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_details/photos/'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='infrastructure_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='keywords',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='number_of_faculty',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='overall_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='photo_video',
            field=models.FileField(blank=True, null=True, upload_to='additional_details/reviews/'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='placement_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='social_life_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='students_in_batch',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='additional_details/videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='total_students',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='upload_type',
            field=models.CharField(blank=True, choices=[('link', 'Link'), ('video/mp4', 'Video (MP4)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='additional_details/videos/'),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='other_links',
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='event_description',
            field=models.CharField(blank=True, choices=[('description1', 'Description 1'), ('description2', 'Description 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='important_news',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='OtherLink',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='other_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
