# Generated by Django 4.2.1 on 2023-12-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_remove_alumni_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegestep2',
            options={},
        ),
    ]
