# Generated by Django 4.2.1 on 2023-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_collegestep2_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegestep1',
            old_name='pan_card_number',
            new_name='college_pan_card_number',
        ),
        migrations.RenameField(
            model_name='collegestep1',
            old_name='pan_card_upload',
            new_name='college_pan_card_upload',
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='name',
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_address_line_1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_address_line_2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_landmark_locality',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='collegestep1',
            name='days_of_operation',
        ),
        migrations.RemoveField(
            model_name='collegestep5',
            name='available_facilities',
        ),
        migrations.RemoveField(
            model_name='collegestep5',
            name='category',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='PhotoCategory',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='days_of_operation',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='available_facilities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collegestep5',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
