# Generated by Django 4.2.1 on 2023-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_rename_answer_collegestep5_faq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestep1',
            name='branch_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep1',
            name='college_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
