# Generated by Django 4.2.1 on 2023-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_collegestep1_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypercentile',
            name='category',
            field=models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='contact_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='days_of_operation',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='facebook_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='instagram_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='linkedin_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='main_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='management_contact',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='management_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='management_role',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='other_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='pinterest_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='youtube_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='date_description',
            field=models.CharField(blank=True, choices=[('description1', 'Description 1'), ('description2', 'Description 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='event_description',
            field=models.CharField(blank=True, choices=[('description1', 'Description 1'), ('description2', 'Description 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='news_category',
            field=models.CharField(blank=True, choices=[('very_imp', 'Very Important'), ('imp', 'Important'), ('medium_imp', 'Medium Important'), ('less_imp', 'Less Important')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='application_process_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='batch_strength',
            field=models.CharField(blank=True, choices=[('strength1', 'Strength 1'), ('strength2', 'Strength 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='category',
            field=models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course',
            field=models.CharField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('duration1', 'Duration 1'), ('duration2', 'Duration 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('mode1', 'Mode 1'), ('mode2', 'Mode 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_branch',
            field=models.CharField(blank=True, choices=[('Degree1', 'Degree 1'), ('Degree2', 'Degree 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_branch_application_process',
            field=models.CharField(blank=True, choices=[('degree1', 'Degree 1'), ('degree2', 'Degree 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_offered',
            field=models.CharField(blank=True, choices=[('degree1', 'Degree 1'), ('degree2', 'Degree 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='eligibility_criteria',
            field=models.CharField(blank=True, choices=[('eligibility1', 'Eligibility 1'), ('eligibility2', 'Eligibility 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='eligibility_criteria_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='parameter_of_cutoffs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='subject',
            field=models.CharField(blank=True, choices=[('subject1', 'Subject 1'), ('subject2', 'Subject 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('category1', 'Category 1'), ('category2', 'Category 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='total_fees',
            field=models.CharField(blank=True, choices=[('fees1', 'Fees 1'), ('fees2', 'Fees 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='background',
            field=models.CharField(blank=True, choices=[('background1', 'Background 1'), ('background2', 'Background 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='base_city',
            field=models.CharField(blank=True, choices=[('city1', 'City 1'), ('city2', 'City 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='degree',
            field=models.CharField(blank=True, choices=[('degree1', 'Degree 1'), ('degree2', 'Degree 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='experience',
            field=models.CharField(blank=True, choices=[('experience1', 'Experience 1'), ('experience2', 'Experience 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='latest_position_achievement',
            field=models.CharField(blank=True, choices=[('experience1', 'Experience 1'), ('experience2', 'Experience 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='specialisation',
            field=models.CharField(blank=True, choices=[('specialisation1', 'Specialisation 1'), ('specialisation2', 'Specialisation 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='year_of_graduation',
            field=models.CharField(blank=True, choices=[('year1', 'Year 1'), ('year2', 'Year 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='average_package',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='course_taken',
            field=models.CharField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='degree_branch',
            field=models.CharField(blank=True, choices=[('degree1', 'Degree 1'), ('degree2', 'Degree 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='highest_package',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_international_offers',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_offers',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_recruiters',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='overall_placement_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='photo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='to_recruiters',
            field=models.CharField(blank=True, choices=[('number1', 'Number 1'), ('number2', 'Number 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year')], null=True),
        ),
        migrations.AlterField(
            model_name='entranceexamchoice',
            name='choice',
            field=models.CharField(choices=[('exam1', 'Exam 1'), ('exam2', 'Exam 2')], unique=True),
        ),
    ]
