# Generated by Django 4.2.1 on 2023-12-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_alter_categorypercentile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypercentile',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], null=True),
        ),
        migrations.AlterField(
            model_name='categorypercentile',
            name='percentile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='GSTIN',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='branch_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_landmark_locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_pan_card_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='college_state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='days_of_operation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='landmark_locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep1',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='ends_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='starts_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='batch_strength',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course',
            field=models.TextField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='cutoff_percentile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_branch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_branch_application_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='degree_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='collegestep3',
            name='entrance_exams',
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='other_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='percentile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep3',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='base_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='latest_position_achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='specialisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='year_of_graduation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='available_facilities',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='average_package',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='course_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='degree_branch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='highest_package',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_faculty',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_international_offers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_offers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='number_of_recruiters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='photo_category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='photo_keywords_meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='students_in_batch',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='to_recruiters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='total_students',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='video_keywords_meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep5',
            name='year_of_study',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep3',
            name='entrance_exams',
            field=models.TextField(blank=True, null=True),
        ),
    ]
