# Generated by Django 4.2.1 on 2023-12-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_categorypercentile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestep4',
            name='base_city',
        ),
        migrations.RemoveField(
            model_name='collegestep4',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='base_city_faculty',
            field=models.CharField(blank=True, choices=[('city1', 'City 1'), ('city2', 'City 2')], null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='faculty_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='faculty_photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
        migrations.AddField(
            model_name='collegestep4',
            name='specialization',
            field=models.CharField(blank=True, choices=[('spec1', 'Specialization 1'), ('spec2', 'Specialization 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='background',
            field=models.CharField(blank=True, choices=[('bg1', 'Background 1'), ('bg2', 'Background 2')], null=True),
        ),
        migrations.AlterField(
            model_name='collegestep4',
            name='experience',
            field=models.CharField(blank=True, choices=[('exp1', 'Experience 1'), ('exp2', 'Experience 2')], null=True),
        ),
    ]
