# Generated by Django 4.2.1 on 2023-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_remove_collegestep4_base_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestep2',
            name='date_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegestep2',
            name='important_news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
