# Generated by Django 4.2.1 on 2023-12-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_alter_collegestep2_date_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestep2',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
