# Generated by Django 4.2.1 on 2023-12-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="study_materials/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Coaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="coaching_logos/")),
                ("short_description", models.TextField(max_length=250)),
                ("detailed_description", models.TextField(max_length=500)),
                ("opens", models.TimeField()),
                ("closes", models.TimeField()),
                ("coaching_main_website", models.URLField()),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("facebook_page", models.URLField()),
                ("instagram_account", models.URLField()),
                ("linkedin_page", models.URLField()),
                ("youtube_channel", models.URLField()),
                ("pinterest_account", models.URLField()),
                ("twitter_handle", models.URLField()),
                ("management_name", models.CharField(max_length=15)),
                ("management_role", models.CharField(max_length=15)),
                ("management_email", models.EmailField(max_length=254)),
                ("management_contact", models.CharField(max_length=15)),
                ("coaching_name", models.CharField(max_length=15)),
                ("coaching_gstin", models.CharField(max_length=10)),
                ("year_of_establishment", models.PositiveIntegerField()),
                ("pan_card_no", models.CharField(max_length=10)),
                ("upload_pan_card", models.FileField(upload_to="coaching_pan_cards/")),
                ("address_line_1", models.TextField(max_length=50)),
                ("address_line_2", models.TextField(max_length=50)),
                ("landmark_locality", models.CharField(max_length=10)),
                ("pincode", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=50)),
                ("location_latitude", models.FloatField()),
                ("location_longitude", models.FloatField()),
                ("locations_city", models.CharField(max_length=50)),
                ("locations_address_line_1", models.TextField(max_length=50)),
                ("locations_address_line_2", models.TextField(max_length=50)),
                ("locations_landmark_locality", models.CharField(max_length=10)),
                ("locations_pincode", models.PositiveIntegerField()),
                ("locations_name_of_branch", models.CharField(max_length=10)),
                ("locations_latitude", models.FloatField()),
                ("locations_longitude", models.FloatField()),
                ("other_exams", models.TextField()),
                ("course_duration", models.CharField(max_length=50)),
                ("course_mode", models.CharField(max_length=50)),
                ("course_description", models.TextField(max_length=500)),
                ("total_fee", models.CharField(max_length=10)),
                ("discount", models.CharField(max_length=10)),
                ("study_material_included", models.BooleanField()),
                ("results_excel_file", models.FileField(upload_to="coaching_results/")),
                (
                    "results_photo",
                    models.ImageField(upload_to="coaching_results_photos/"),
                ),
                ("results_name", models.CharField(max_length=10)),
                ("results_all_india_rank", models.CharField(max_length=10)),
                ("results_base_city", models.CharField(max_length=50)),
                ("results_testimonial", models.TextField()),
                ("faculties_photo", models.ImageField(upload_to="coaching_faculties/")),
                ("faculties_name", models.CharField(max_length=10)),
                ("faculties_background", models.CharField(max_length=50)),
                ("faculties_experience", models.CharField(max_length=50)),
                ("faculties_base_city", models.CharField(max_length=50)),
                ("faculties_links", models.TextField()),
                ("photos_photo", models.ImageField(upload_to="coaching_photos/")),
                ("photos_description", models.TextField(max_length=250)),
                ("photos_keywords_meta_tags", models.TextField()),
                ("videos_link", models.URLField()),
                ("videos_file", models.FileField(upload_to="coaching_videos/")),
                ("videos_description", models.TextField(max_length=250)),
                ("videos_keywords_meta_tags", models.TextField()),
                (
                    "videos_thumbnail",
                    models.ImageField(upload_to="coaching_videos_thumbnails/"),
                ),
                ("reviews_name", models.CharField(max_length=10)),
                ("reviews_year_of_study", models.CharField(max_length=50)),
                ("reviews_overall_rating", models.PositiveIntegerField()),
                ("reviews_competitive_environment", models.PositiveIntegerField()),
                ("reviews_faculty", models.PositiveIntegerField()),
                ("reviews_infrastructure", models.PositiveIntegerField()),
                ("reviews_study_material", models.PositiveIntegerField()),
                ("reviews_peer_learning", models.PositiveIntegerField()),
                ("reviews_detailed_description", models.TextField()),
                ("reviews_links", models.URLField()),
                (
                    "reviews_photo_video",
                    models.ImageField(upload_to="coaching_reviews_photo_video/"),
                ),
                ("checklist_students_in_batch", models.CharField(max_length=5)),
                (
                    "checklist_total_students_in_coaching",
                    models.CharField(max_length=5),
                ),
                ("checklist_number_of_faculty", models.CharField(max_length=5)),
                ("faqs_question", models.TextField()),
                ("faqs_answer", models.TextField()),
                (
                    "checklist_available_facilities",
                    models.ManyToManyField(
                        related_name="coaching_checklist_facilities",
                        to="coaching.facility",
                    ),
                ),
                (
                    "coaching_for_exams",
                    models.ManyToManyField(
                        related_name="coaching_for_exams", to="coaching.course"
                    ),
                ),
                (
                    "courses_for_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_courses_for_exam",
                        to="coaching.course",
                    ),
                ),
                ("days_of_operation", models.ManyToManyField(to="coaching.weekday")),
                (
                    "faculties_specialisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_faculties_specialisation",
                        to="coaching.course",
                    ),
                ),
                (
                    "locations_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_locations_state",
                        to="coaching.state",
                    ),
                ),
                (
                    "other_links",
                    models.ManyToManyField(
                        related_name="coaching_links", to="coaching.link"
                    ),
                ),
                (
                    "photos_category",
                    models.ManyToManyField(
                        related_name="coaching_photos_categories",
                        to="coaching.category",
                    ),
                ),
                (
                    "results_college_secured",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_results_college_secured",
                        to="coaching.college",
                    ),
                ),
                (
                    "results_exam_cracked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_results_exam_cracked",
                        to="coaching.exam",
                    ),
                ),
                (
                    "reviews_course_taken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_reviews_course_taken",
                        to="coaching.course",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_state",
                        to="coaching.state",
                    ),
                ),
                (
                    "study_materials",
                    models.ManyToManyField(
                        related_name="coaching_study_materials",
                        to="coaching.studymaterial",
                    ),
                ),
            ],
        ),
    ]
