# Generated by Django 4.2.1 on 2023-12-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingStep1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="coaching_logos/")),
                ("short_description", models.TextField(max_length=250)),
                ("detailed_description", models.TextField(max_length=500)),
                ("opens", models.TimeField()),
                ("closes", models.TimeField()),
                ("coaching_main_website", models.URLField()),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("days_of_operation", models.ManyToManyField(to="coaching.weekday")),
            ],
        ),
        migrations.CreateModel(
            name="CoachingStep2",
            fields=[
                (
                    "coaching_step1",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="coaching.coachingstep1",
                    ),
                ),
                ("management_name", models.CharField(max_length=15)),
                ("management_role", models.CharField(max_length=15)),
                ("management_email", models.EmailField(max_length=254)),
                ("management_contact", models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name="Coaching",
        ),
        migrations.CreateModel(
            name="CoachingStep3",
            fields=[
                (
                    "coaching_step2",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="coaching.coachingstep2",
                    ),
                ),
                ("coaching_name", models.CharField(max_length=15)),
                ("coaching_gstin", models.CharField(max_length=10)),
                ("year_of_establishment", models.PositiveIntegerField()),
                ("pan_card_no", models.CharField(max_length=10)),
                ("upload_pan_card", models.FileField(upload_to="coaching_pan_cards/")),
                ("address_line_1", models.TextField(max_length=50)),
                ("address_line_2", models.TextField(max_length=50)),
                ("landmark_locality", models.CharField(max_length=10)),
                ("pincode", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=50)),
                ("location_latitude", models.FloatField()),
                ("location_longitude", models.FloatField()),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaching_state",
                        to="coaching.state",
                    ),
                ),
            ],
        ),
    ]
