# Generated by Django 4.2.1 on 2023-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0002_coachingstep1_coachingstep2_delete_coaching_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingstep1",
            name="facebook_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="instagram_account",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="linkedin_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="other_links",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="pinterest_account",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="twitter_handle",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="youtube_channel",
            field=models.URLField(blank=True, null=True),
        ),
    ]
