# Generated by Django 4.2.1 on 2023-12-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0003_coachingstep1_facebook_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingstep1",
            name="address_line_1",
            field=models.CharField(blank=True, default="Hydrabad", null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="address_line_1_loc",
            field=models.CharField(blank=True, default="Hyderabad", null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="address_line_2",
            field=models.CharField(blank=True, default="Hydrabad", null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="address_line_2_loc",
            field=models.CharField(blank=True, default="Hyderabad", null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="branch_name",
            field=models.CharField(blank=True, default="Hyderabad", null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="city",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="coaching_gstin",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="coaching_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="establishment_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="landmark",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="pan_card_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="pan_card_upload",
            field=models.FileField(blank=True, null=True, upload_to="pan_cards/"),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="pincode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="role",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("State1", "State 1"), ("State2", "State 2")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="closes",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="coaching_main_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="contact_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="days_of_operation",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to="coaching.coachingstep1"
            ),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="detailed_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="coaching_logos/"),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="opens",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="other_links",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep2",
            name="management_contact",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep2",
            name="management_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep2",
            name="management_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep2",
            name="management_role",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="address_line_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="address_line_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="city",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="coaching_gstin",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="coaching_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="landmark_locality",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="pan_card_no",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="pincode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaching_state",
                to="coaching.state",
            ),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="upload_pan_card",
            field=models.FileField(
                blank=True, null=True, upload_to="coaching_pan_cards/"
            ),
        ),
        migrations.AlterField(
            model_name="coachingstep3",
            name="year_of_establishment",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="study_materials/"),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weekday",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
