# Generated by Django 4.2.1 on 2023-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0004_coachingstep1_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekday",
            name="name",
        ),
        migrations.AddField(
            model_name="weekday",
            name="day_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="coachingstep1",
            name="days_of_operation",
            field=models.ManyToManyField(to="coaching.weekday"),
        ),
    ]
