# Generated by Django 4.2.1 on 2023-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0005_remove_weekday_name_weekday_day_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachingstep2",
            name="management_contact",
        ),
        migrations.RemoveField(
            model_name="coachingstep2",
            name="management_email",
        ),
        migrations.RemoveField(
            model_name="coachingstep2",
            name="management_name",
        ),
        migrations.RemoveField(
            model_name="coachingstep2",
            name="management_role",
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="all_india_rank",
            field=models.CharField(
                blank=True,
                choices=[("rank1", "Rank 1"), ("rank2", "Rank 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="background",
            field=models.CharField(
                blank=True,
                choices=[("bg1", "Background 1"), ("bg2", "Background 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="base_city_faculty",
            field=models.CharField(
                blank=True,
                choices=[("city1", "City 1"), ("city2", "City 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="base_city_result",
            field=models.CharField(
                blank=True,
                choices=[("city1", "City 1"), ("city2", "City 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="coaching_for_exams",
            field=models.CharField(
                blank=True,
                choices=[
                    ("design", "Design"),
                    ("engineering", "Engineering"),
                    ("etc", "Etc."),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="college_secured",
            field=models.CharField(
                blank=True,
                choices=[("college1", "College 1"), ("college2", "College 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="course_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="course_duration",
            field=models.CharField(
                blank=True,
                choices=[("duration1", "Duration 1"), ("duration2", "Duration 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="course_for_exam",
            field=models.CharField(
                blank=True,
                choices=[
                    ("course1", "Course 1"),
                    ("course2", "Course 2"),
                    ("course3", "Course 3"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="course_mode",
            field=models.CharField(
                blank=True,
                choices=[("mode1", "Mode 1"), ("mode2", "Mode 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="discount",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="exam_cracked",
            field=models.CharField(
                blank=True,
                choices=[("exam1", "Exam 1"), ("exam2", "Exam 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="exams_who_can_refer",
            field=models.CharField(
                blank=True,
                choices=[("exam1", "Exam 1"), ("exam2", "Exam 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="excel_file",
            field=models.FileField(blank=True, null=True, upload_to="result_files/"),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[("exp1", "Experience 1"), ("exp2", "Experience 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="faculty_links",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="faculty_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="faculty_photo",
            field=models.ImageField(blank=True, null=True, upload_to="faculty_photos/"),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="keywords_meta_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="links",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="material_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="material_file",
            field=models.FileField(blank=True, null=True, upload_to="material_files/"),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="other_exams",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="result_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="result_photo",
            field=models.ImageField(blank=True, null=True, upload_to="result_photos/"),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="specialization",
            field=models.CharField(
                blank=True,
                choices=[("spec1", "Specialization 1"), ("spec2", "Specialization 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="study_material_included",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="testimonial",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep2",
            name="total_fee",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
