# Generated by Django 4.2.1 on 2023-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0006_remove_coachingstep2_management_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="coachingstep3",
            old_name="address_line_1",
            new_name="faq_answer",
        ),
        migrations.RenameField(
            model_name="coachingstep3",
            old_name="address_line_2",
            new_name="faq_question",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="city",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="coaching_gstin",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="coaching_name",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="landmark_locality",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="location_latitude",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="location_longitude",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="pan_card_no",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="state",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="upload_pan_card",
        ),
        migrations.RemoveField(
            model_name="coachingstep3",
            name="year_of_establishment",
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="available_facilities",
            field=models.ManyToManyField(blank=True, to="coaching.facility"),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="competitive_environment",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="course_taken",
            field=models.CharField(
                blank=True,
                choices=[("course1", "Course 1"), ("course2", "Course 2")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="faculty_rating",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="infrastructure_rating",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="number_of_faculty",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="overall_rating",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="peer_learning_rating",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="photo_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="photo_keywords_meta_tags",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="review_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="review_links",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="review_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="review_photo_or_video",
            field=models.FileField(blank=True, null=True, upload_to="review_files/"),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="students_in_batch",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="study_material_rating",
            field=models.IntegerField(
                blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="total_students_in_coaching",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="video_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="video_keywords_meta_tags",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="video_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="year_of_study",
            field=models.CharField(
                blank=True,
                choices=[("year1", "Year 1"), ("year2", "Year 2")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep3",
            name="photo_category",
            field=models.ManyToManyField(blank=True, to="coaching.photocategory"),
        ),
    ]
