# Generated by Django 4.2.1 on 2023-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0007_photocategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingstep1",
            name="contact_number_mang",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="email_mang",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
