# Generated by Django 4.2.1 on 2023-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0008_coachingstep1_contact_number_mang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingstep1",
            name="landmark_loc",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="latitude_loc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="longitude_loc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coachingstep1",
            name="pincode_loc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
