# Generated by Django 4.2.1 on 2023-12-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_coachingstep1_landmark_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstep1',
            name='address_line_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='address_line_1_loc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='address_line_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='address_line_2_loc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='branch_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
