# Generated by Django 4.2.1 on 2023-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0010_alter_coachingstep1_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstep1',
            name='days_of_operation',
            field=models.ManyToManyField(blank=True, null=True, to='coaching.weekday'),
        ),
    ]
