# Generated by Django 4.2.1 on 2023-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0012_rename_total_students_in_coaching_coachingstep3_total_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstep1',
            name='coaching_main_website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='facebook_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='instagram_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='linkedin_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='other_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='pinterest_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='twitter_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep1',
            name='youtube_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='review_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
