# Generated by Django 4.2.1 on 2023-12-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0013_alter_coachingstep1_coaching_main_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstep1',
            name='state',
            field=models.CharField(blank=True, choices=[('State1', 'State 1'), ('State2', 'State 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='all_india_rank',
            field=models.CharField(blank=True, choices=[('rank1', 'Rank 1'), ('rank2', 'Rank 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='background',
            field=models.CharField(blank=True, choices=[('bg1', 'Background 1'), ('bg2', 'Background 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='base_city_faculty',
            field=models.CharField(blank=True, choices=[('city1', 'City 1'), ('city2', 'City 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='base_city_result',
            field=models.CharField(blank=True, choices=[('city1', 'City 1'), ('city2', 'City 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='coaching_for_exams',
            field=models.CharField(blank=True, choices=[('design', 'Design'), ('engineering', 'Engineering'), ('etc', 'Etc.')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='college_secured',
            field=models.CharField(blank=True, choices=[('college1', 'College 1'), ('college2', 'College 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='course_duration',
            field=models.CharField(blank=True, choices=[('duration1', 'Duration 1'), ('duration2', 'Duration 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='course_for_exam',
            field=models.CharField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2'), ('course3', 'Course 3')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('mode1', 'Mode 1'), ('mode2', 'Mode 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='discount',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='exam_cracked',
            field=models.CharField(blank=True, choices=[('exam1', 'Exam 1'), ('exam2', 'Exam 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='exams_who_can_refer',
            field=models.CharField(blank=True, choices=[('exam1', 'Exam 1'), ('exam2', 'Exam 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='experience',
            field=models.CharField(blank=True, choices=[('exp1', 'Experience 1'), ('exp2', 'Experience 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='faculty_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='material_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='result_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='specialization',
            field=models.CharField(blank=True, choices=[('spec1', 'Specialization 1'), ('spec2', 'Specialization 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='study_material_included',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep2',
            name='total_fee',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='available_facilities',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='course_taken',
            field=models.CharField(blank=True, choices=[('course1', 'Course 1'), ('course2', 'Course 2')], null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='number_of_faculty',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='photo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='photo_keywords_meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='review_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='review_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='students_in_batch',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='total_students',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='video_keywords_meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstep3',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('year1', 'Year 1'), ('year2', 'Year 2')], null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
