# Generated by Django 4.2.1 on 2023-12-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0015_coachingstep1_city_loc_coachingstep1_state_loc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingSteps2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaching_for_exams', models.TextField(blank=True, null=True)),
                ('other_exams', models.TextField(blank=True, null=True)),
                ('course_for_exam', models.TextField(blank=True, null=True)),
                ('course_duration', models.TextField(blank=True, null=True)),
                ('course_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('total_fee', models.CharField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, null=True)),
                ('study_material_included', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], null=True)),
                ('material_file', models.FileField(blank=True, null=True, upload_to='material_files/')),
                ('material_description', models.TextField(blank=True, null=True)),
                ('keywords_meta_tags', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('exams_who_can_refer', models.CharField(blank=True, choices=[('exam1', 'Exam 1'), ('exam2', 'Exam 2')], null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='result_files/')),
                ('result_photo', models.ImageField(blank=True, null=True, upload_to='result_photos/')),
                ('result_name', models.CharField(blank=True, null=True)),
                ('college_secured', models.TextField(blank=True, null=True)),
                ('exam_cracked', models.CharField(blank=True, choices=[('exam1', 'Exam 1'), ('exam2', 'Exam 2')], null=True)),
                ('all_india_rank', models.TextField(blank=True, null=True)),
                ('base_city_result', models.TextField(blank=True, null=True)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('faculty_photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('faculty_name', models.CharField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('base_city_faculty', models.TextField(blank=True, null=True)),
                ('faculty_links', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingSteps3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_description', models.TextField(blank=True, null=True)),
                ('photo_category', models.TextField(blank=True, null=True)),
                ('photo_keywords_meta_tags', models.TextField(blank=True, null=True)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_keywords_meta_tags', models.TextField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('review_name', models.CharField(blank=True, null=True)),
                ('year_of_study', models.TextField(blank=True, null=True)),
                ('course_taken', models.TextField(blank=True, null=True)),
                ('competitive_environment', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('faculty_rating', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('infrastructure_rating', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('peer_learning_rating', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('study_material_rating', models.IntegerField(blank=True, choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], null=True)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('review_links', models.TextField(blank=True, null=True)),
                ('review_photo_or_video', models.FileField(blank=True, null=True, upload_to='review_files/')),
                ('available_facilities', models.CharField(blank=True, null=True)),
                ('students_in_batch', models.CharField(blank=True, null=True)),
                ('total_students', models.CharField(blank=True, null=True)),
                ('number_of_faculty', models.CharField(blank=True, null=True)),
                ('faq_question', models.TextField(blank=True, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CoachingStep1',
            new_name='CoachingSteps1',
        ),
        migrations.RemoveField(
            model_name='coachingstep2',
            name='coaching_step1',
        ),
        migrations.RemoveField(
            model_name='coachingstep3',
            name='coaching_step2',
        ),
        migrations.RemoveField(
            model_name='coachingstep3',
            name='photo_category',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.DeleteModel(
            name='CoachingStep2',
        ),
        migrations.DeleteModel(
            name='CoachingStep3',
        ),
    ]
